- name: Install fish with homebrew
  homebrew:
    name: fish
    state: present

- name: Add fish executable to /etc/shells
  become: yes
  lineinfile:
    line: /usr/local/bin/fish
    dest: /etc/shells
    state: present

- name: Set fish as default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/fish

- name: Setup fish symlinks
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: '{{ DOTFILES_REPO }}/roles/fish/files/functions',   dest: '~/.config/fish/functions'}
    - { src: '{{ DOTFILES_REPO }}/roles/fish/files/config.fish', dest: '~/.config/fish/config.fish'}
    - { src: '{{ DOTFILES_REPO }}/roles/fish/files/plugins',     dest: '~/.config/fish/fish_plugins'}
