- name: Extend sudo timeout
  become: yes
  ansible.builtin.lineinfile:
    line: Defaults timestamp_timeout=120 # 2 hours
    path: /private/etc/sudoers.d/timeout
    state: present
    create: yes

- name: Install fish and starship with homebrew
  community.general.homebrew:
    name:
      - fish
      - starship
    state: present

- name: Add fish executable to /etc/shells
  become: yes
  ansible.builtin.lineinfile:
    line: /usr/local/bin/fish
    path: /etc/shells
    state: present

- name: Set fish as default shell
  become: yes
  ansible.builtin.user:
    name: sam_hosseini
    shell: /usr/local/bin/fish

- name: Create fish config directory
  ansible.builtin.file:
    path: ~/.config/fish
    state: directory

- name: Setup fish symlinks
  ansible.builtin.file:
    src: '{{ item.src }}'
    path: '{{ item.path }}'
    state: link
  loop:
    - { src: '{{ DOTFILES_REPO }}/roles/fish/files/functions',    path: '~/.config/fish/functions'}
    - { src: '{{ DOTFILES_REPO }}/roles/fish/files/config.fish',  path: '~/.config/fish/config.fish'}
    - { src: '{{ DOTFILES_REPO }}/roles/fish/files/plugins.fish', path: '~/.config/fish/fish_plugins'}

- name: Download fisher function
  ansible.builtin.get_url:
    url: https://git.io/fisher
    dest: '{{ DOTFILES_REPO }}/roles/fish/files/functions/fisher.fish'

- name: Install fisher plugins
  ansible.builtin.shell:
    executable: /usr/local/bin/fish
    cmd: 'fisher update'
    creates: ~/.config/fish/conf.d/dracula.fish

- name: Disable shell login message
  ansible.builtin.copy:
    src: /dev/null
    dest: ~/.hushlogin
