"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Indentation configurations
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set expandtab " tab becomes a shortcut to insert four spaces
set shiftwidth=4 " number of spaces to use for auto indent
set softtabstop=4 " number of spaces in tab when editing
set tabstop=4 " number of VISUAL spaces for each tab respresentation
