- name: Install vscode with homebrew
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present

- name: Create vscode config directory
  ansible.builtin.file:
    path: '~/Library/Application Support/Code/User'
    state: directory

- name: Setup vscode symlink
  ansible.builtin.file:
    src: '{{ DOTFILES_REPO }}/roles/vscode/files/settings.json'
    path: '~/Library/Application Support/Code/User/settings.json'
    state: link

- name: Get adhoc vscode extensions
  ansible.builtin.find:
    paths: ~/.vscode/extensions/
    file_type: directory
    use_regex: yes
    excludes: '{{ vscode_extensions }}'
    patterns: '.*'
  register: adhoc_vscode_extensions

- name: Delete adhoc vscode extensions
  loop: '{{ adhoc_vscode_extensions.files }}'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: absent

- name: Install vscode extensions
  loop: "{{ vscode_extensions }}"
  ansible.builtin.command:
    cmd: code --install-extension {{ item }}
    creates: ~/.vscode/extensions/{{ item }}*
