- name: Check gatekeeper
  ansible.builtin.command:
    cmd: spctl --status
  register: gatekeeper_status
  failed_when: false
  changed_when: false

- name: Disable gatekeeper
  ansible.builtin.command:
    cmd: spctl --master-disable # gets rid of unidentified developer warning when opening an app
  become: yes
  when: gatekeeper_status.stdout != 'assessments disabled'

- name: Setup login items
  ansible.builtin.command:
    cmd: osascript '{{ DOTFILES_REPO }}/roles/macos/files/login_items.applescript'
  register: result
  changed_when: result.rc != 0

- name: Setup Cloudflare DNS servers
  ansible.builtin.command:
    cmd: networksetup -setdnsservers Wi-Fi {{ item }}
  with_items:
    - Empty
    - 1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001 # https://one.one.one.one/dns/
  register: result
  changed_when: result.rc != 0
