- name: Check gatekeeper
  ansible.builtin.command:
    cmd: spctl --status
  register: gatekeeper_status
  failed_when: false
  changed_when: false

- name: Disable gatekeeper
  ansible.builtin.command:
    cmd: spctl --master-disable # gets rid of unidentified developer warning when opening an app
  become: yes
  when: gatekeeper_status.stdout != 'assessments disabled'

- name: Setup login items
  ansible.builtin.command:
    cmd: osascript '{{ DOTFILES_REPO }}/roles/macos/files/login_items.applescript'
  register: result
  changed_when: result.rc != 0

- name: Setup Cloudflare DNS servers
  ansible.builtin.command:
    cmd: networksetup -setdnsservers Wi-Fi {{ item }}
  with_items:
    - Empty
    - 1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001 # https://one.one.one.one/dns/
  register: result
  changed_when: result.rc != 0

- name: Setup macOS preferences
  community.general.osx_defaults:
    domain: '{{ item.domain }}'
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
    state: present
  with_items:
    # Disable natural scrolling
    - { domain: 'NSGlobalDomain', key: 'com.apple.swipescrolldirection', type: 'bool', value: 'false'}
    # Enable full keyboard access for all controls which enables Tab selection in modal dialogs
    - { domain: 'NSGlobalDomain', key: 'AppleKeyboardUIMode', type: 'int', value: '3'}
    # Configure keyboard repeat https://apple.stackexchange.com/a/83923/200178
    - { domain: 'NSGlobalDomain', key: 'InitialKeyRepeat', type: 'int', value: '15'}
    - { domain: 'NSGlobalDomain', key: 'KeyRepeat', type: 'int', value: '2'}
    # Disable "Correct spelling automatically"
    - { domain: 'NSGlobalDomain', key: 'NSAutomaticSpellingCorrectionEnabled', type: 'bool', value: 'false'}
    # Enable tap to click
    - { domain: 'com.apple.AppleMultitouchTrackpad', key: 'Clicking', type: 'bool', value: 'true'}
    # Show battery percentage in menu bar
    - { domain: 'com.apple.systemuiserver', key: 'NSStatusItem Visible com.apple.menuextra.battery', type: 'bool', value: 'true'}
    - { domain: 'com.apple.menuextra.battery', key: 'ShowPercent', type: 'string', value: 'YES'}
    # Disable screenshot preview thumbnails
    - { domain: 'com.apple.screencapture', key: 'show-thumbnail', type: 'bool', value: 'false'}
    # Save screenshots to Downloads folder
    - { domain: 'com.apple.screencapture', key: 'location', type: 'string', value: '{{ HOME_DIR }}/Downloads'}

- name: Setup dock preferences
  community.general.osx_defaults:
    domain: com.apple.dock
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
    state: present
  with_items:
    # Don’t show recent applications in Dock
    - { key: 'show-recents', type: 'bool', value: 'false'}
    # Set the icon size of Dock items to 36 pixels
    - { key: 'tilesize', type: 'int', value: '36'}
    # Remove all default app icons from the Dock
    - { key: 'persistent-apps', type: 'array', value: '[]'}
    - { key: 'recent-apps', type: 'array', value: '[]'}
    # Show only open applications in the Dock
    - { key: 'static-only', type: 'bool', value: 'true'}
    # Don’t animate opening applications from the Dock
    - { key: 'launchanim', type: 'bool', value: 'false'}
    # Automatically hide and show the Dock
    - { key: 'autohide', type: 'bool', value: 'true'}
    # Remove the auto-hiding Dock delay
    - { key: 'autohide-delay', type: 'float', value: '0'}
    # Disable the Launchpad gesture (pinch with thumb and three fingers)
    - { key: 'showLaunchpadGestureEnabled', type: 'int', value: '0'}
    # Disable automatically rearranging of Spaces based on most recent use
    - { key: 'mru-spaces', type: 'bool', value: 'false'}
