- name: Install karabiner with homebrew
  community.general.homebrew_cask:
    name: karabiner-elements
    state: present

- name: Setup karabiner symlink
  ansible.builtin.file:
    src: '{{ DOTFILES_REPO }}/roles/karabiner/files'
    path: ~/.config/karabiner
    state: link
