- name: Install git and delta with homebrew
  community.general.homebrew:
    name:
      - git
      - git-delta
    state: present

- name: Create git config directory
  ansible.builtin.file:
    path: ~/.config/git
    state: directory

- name: Install git config template
  ansible.builtin.template:
    src: '{{ DOTFILES_REPO }}/roles/git/templates/config.j2'
    dest: ~/.config/git/config
