- name: Install vim with homebrew
  community.general.homebrew:
    name: vim
    state: present

- name: Install vim plugin manager
  ansible.builtin.git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: ~/.vim/bundle/Vundle.vim
    update: no

- name: Install vim plugins
  ansible.builtin.command:
    cmd: vim --not-a-term +PluginInstall +qall
  changed_when: false # until replaced with  vim-plug
