- name: Install neovim with homebrew
  community.general.homebrew:
    name:
      - luajit          # First, neovim's dependency, luajit => https://bit.ly/3aafYS8
      - nvim
    state: head         # HEAD is needed for vscode-neovim until a stable 0.5 release => https://bit.ly/3r4Wqpo

- name: Create nvim config directory
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory

- name: Install nvim config template
  ansible.builtin.template:
    src: '{{ DOTFILES_REPO }}/roles/nvim/templates/nvim.j2'
    dest: '~/.config/nvim/init.vim'

- name: Create vim-plug directory
  ansible.builtin.file:
    path: ~/.config/nvim/autoload
    state: directory

- name: Install vim-plug
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    dest: ~/.config/nvim/autoload/plug.vim

- name: Install nvim plugins
  ansible.builtin.command:
    cmd: nvim +PlugInstall +qall
  register: result
  changed_when: '"Resolving" in result.stdout'
