- name: Install neovim with homebrew
  community.general.homebrew:
    name:
      - luajit          # First, neovim's dependency, luajit => https://bit.ly/3aafYS8
      - nvim
    state: head         # HEAD is needed for vscode-neovim until a stable 0.5 release => https://bit.ly/3r4Wqpo

- name: Create nvim config directory
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory

- name: Setup nvim symlink
  ansible.builtin.file:
    src: '{{ DOTFILES_REPO }}/roles/nvim/files/init.vim'
    path: '~/.config/nvim/init.vim'
    state: link

- name: Create vim-plug directory
  ansible.builtin.file:
    path: ~/.config/nvim/autoload
    state: directory

- name: Install vim-plug
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    dest: ~/.config/nvim/autoload/plug.vim
