- name: Install neovim with homebrew
  community.general.homebrew:
    name:
      - luajit          # First, neovim's dependency, luajit => https://bit.ly/3aafYS8
      - nvim
    state: head         # HEAD is needed for vscode-neovim until a stable 0.5 release => https://bit.ly/3r4Wqpo

- name: Create nvim config directory
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory

- name: Setup nvim symlink
  ansible.builtin.file:
    src: '{{ DOTFILES_REPO }}/roles/nvim/files/init.vim'
    path: '~/.config/nvim/init.vim'
    state: link
